-- SYSTEM 계정에서 실행해서 새로운 계정 생성
-- CREATE USER FD IDENTIFIED BY FD;
-- 새로운 계정 접속
-- GRANT RESOURCE, CONNECT TO FD;


----------------------------------------------------------
--------------------- USER 관련 테이블 ---------------------
----------------------------------------------------------

CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(13),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(150),
    USER_ENROLL_DATE DATE DEFAULT SYSDATE,
    USER_MODIFY_DATE DATE DEFAULT SYSDATE,
    USER_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(USER_STATUS IN('Y', 'N')),
    USER_ROLE VARCHAR2(20) DEFAULT 'ROLE_USER',
    USER_COIN NUMBER DEFAULT 0
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원ID';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원PWD';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원명';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.USER_ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.USER_MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.USER_STATUS IS '회원상태(Y/N)';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '회원타입';
COMMENT ON COLUMN MEMBER.USER_COIN IS '캐리머니';

CREATE SEQUENCE SEQ_UNO;

INSERT INTO MEMBER VALUES(
    SEQ_UNO.NEXTVAL,'admin', '1234', '관리자', '010-1234-5678', 'admin@iei.or.kr', '서울시 강남구', SYSDATE, SYSDATE, DEFAULT, 'ROLE_ADMIN', DEFAULT
);

INSERT INTO MEMBER VALUES(
    SEQ_UNO.NEXTVAL, 'ismoon', '1234', '일반회원', '010-1111-2222', 'ismoon@iei.or.kr', '서울시 동작구', SYSDATE, SYSDATE, DEFAULT, DEFAULT, 100000
);

INSERT INTO MEMBER VALUES(
    SEQ_UNO.NEXTVAL, 'creator', '1234', '창작자', '010-3333-5555', 'creator@iei.or.kr', '서울시 송파구', SYSDATE, SYSDATE, DEFAULT, 'ROLE_CREATOR', DEFAULT
);

COMMIT;

-- 멤버 조회
-- SELECT * FROM MEMBER WHERE USER_ID=? AND USER_PWD=? AND USER_STATUS='Y'

-- 멤버 추가
-- INSERT INTO MEMBER VALUES(SEQ_UNO.NEXTVAL,?,?,?,?,?,?,SYSDATE,SYSDATE,DEFAULT,DEFAULT,DEFAULT)

-- 멤버 찾기
-- SELECT * FROM MEMBER WHERE USER_ID=?

-- 멤버 패스워드 변경
-- UPDATE MEMBER SET PASSWORD=? WHERE USER_ID=?

-- 멤버 수정
-- UPDATE MEMBER SET USER_NAME=?,PHONE=?,EMAIL=?,ADDRESS=?,MODIFY_DATE=SYSDATE WHERE USER_ID=?

-- 멤버 삭제
-- UPDATE MEMBER SET STATUS=? WHERE USER_ID=?

-- 멤버 창작자로 변경?
-- 멤버 캐리머니 값 변경?


--------------------------------------------------------------------
---------------------- project test 관련 테이블 ----------------------
--------------------------------------------------------------------

-- 테스트용
CREATE TABLE CARRYFUNDING_PROJECT(
    PROJECT_NO NUMBER PRIMARY KEY,
    PROJECT_TITLE VARCHAR2(200) NOT NULL,
    PROJECT_COMPANY VARCHAR2(100),
    TARGET_AMOUNT NUMBER NOT NULL,
    REACH_AMOUNT NUMBER NOT NULL,
    PROJECT_ENROLL_DATE DATE DEFAULT SYSDATE,
    PROJECT_MODIFY_DATE DATE DEFAULT SYSDATE,
    PROJECT_END_DATE DATE NOT NULL,
    IMG_NAME VARCHAR2(100),
    VIDEO_NAME VARCHAR2(100),
    PROJECT_CONTENT VARCHAR2(4000),
    PROJECT_CHECK VARCHAR2(1) DEFAULT 'N' CHECK (PROJECT_CHECK IN('Y', 'N')),
    PROJECT_COUNT NUMBER DEFAULT 0,
    PROJECT_LIKE NUMBER DEFAULT 0,
    PROJECT_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (PROJECT_STATUS IN('Y', 'N')),
    CREATOR_NO NUMBER NOT NULL,
    CONSTRAINT FK_PROJECT_WRITER FOREIGN KEY(CREATOR_NO) REFERENCES MEMBER(USER_NO) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_PROJECT_NO;

COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_NO" IS '프로젝트번호';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_TITLE" IS '프로젝트제목';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_COMPANY" IS '업체명';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."TARGET_AMOUNT" IS '목표금액';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."REACH_AMOUNT" IS '현재도달금액';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_ENROLL_DATE" IS '프로젝트시작날짜';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_MODIFY_DATE" IS '프로젝트정보수정날짜';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_END_DATE" IS '프로젝트종료날짜';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."IMG_NAME" IS '이미지등록이름';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."VIDEO_NAME" IS '동영상등록이름';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_CONTENT" IS '프로젝트내용';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_CHECK" IS '프로젝트심사상태';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_COUNT" IS '프로젝트조회수';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_LIKE" IS '좋아요등록수';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_STATUS" IS '프로젝트상태';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."CREATOR_NO" IS '창작자번호';

INSERT INTO CARRYFUNDING_PROJECT VALUES(
    SEQ_PROJECT_NO.NEXTVAL,
    '프로젝트TEST',
    'CARRY',
    1000000,
    0,
    DEFAULT,
    DEFAULT,
    '21/01/25',
    '이미지.JPG',
    '비디오.AVI',
    '프로젝트 TEST 입니다. 무슨 내용을 넣어야 할까요? 과연 엔터도 먹을까요?
    줄바꿈 같은것도 직접해야할까? 고민이네요ㅋㅋㅋ',
    'Y',
    DEFAULT,
    DEFAULT,
    DEFAULT,
    1
);

INSERT INTO CARRYFUNDING_PROJECT VALUES(
    SEQ_PROJECT_NO.NEXTVAL,
    'TEST2',
    'ISMOON',
    10000000,
    0,
    DEFAULT,
    DEFAULT,
    '21/01/30',
    '이미지1.JPG',
    '비디오1.AVI',
    '프로젝트 TEST222 입니다. 무슨 내용을 넣어야 할까요? 과연 엔터도 먹을까요?
    줄바꿈 같은것도 직접해야할까? 고민이네요ㅋㅋㅋ',
    'Y',
    DEFAULT,
    DEFAULT,
    DEFAULT,
    2
);

-- 프로젝트 글 조회하기
SELECT P.PROJECT_NO, P.PROJECT_TITLE, M.USER_ID, P.PROJECT_COMPANY, P.TARGET_AMOUNT, P.REACH_AMOUNT, P.PROJECT_ENROLL_DATE, P.PROJECT_MODIFY_DATE, P.PROJECT_END_DATE, P.IMG_NAME, P.VIDEO_NAME, P.PROJECT_CONTENT, P.PROJECT_COUNT, P.PROJECT_LIKE
FROM CARRYFUNDING_PROJECT P
JOIN MEMBER M ON(P.CREATOR_NO = M.USER_NO)
WHERE P.PROJECT_STATUS = 'Y' AND P.PROJECT_CHECK = 'Y' AND P.PROJECT_NO = ?


--------------------------------------------------------------------
------------------------- Board 관련 테이블 --------------------------
--------------------------------------------------------------------

